services:
  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=production
