apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: johnkrishh049/terraform-aks-microservices-backend:latest
          ports:
            - containerPort: 4000
              name: http  # <-- Added port name
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: microservices
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http  # <-- Use the port name instead of number
  type: LoadBalancer