name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account set --subscription c6dd8e77-6e8a-4de1-8b4d-7d15d57dbb71
          az aks get-credentials --resource-group aks-rg --name aks-vithu --overwrite-existing
          kubectl apply -f k8s-deployments/

